[project]
name = "multiple-agents-on-single-a2a-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk>=0.3.1",
    "google-adk>=1.11.0",
]
